In [21]:
import numpy as np
import random as ran

In [18]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
def h_eye(value):
    box = []
    for i in range(value):
        mini = []
        for j in range(value):
            if i==j:
                mini.append(1)
            else:
                mini.append(0)
        box.append(mini)
        
    print(box)

In [47]:
h_eye(3)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [31]:
np.linspace(5,100,7)

array([  5.        ,  20.83333333,  36.66666667,  52.5       ,
        68.33333333,  84.16666667, 100.        ])

In [45]:
def h_linspace(start,end,cnt):
    box = []
    for i in range(cnt):
        box.append(start+((end-start)/(cnt-1))*i)
        
    print(box)

In [46]:
h_linspace(5,100,7)

[5.0, 20.833333333333336, 36.66666666666667, 52.5, 68.33333333333334, 84.16666666666667, 100.0]


In [50]:
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.ndim

3

In [60]:
def h_ndim(data) :
    count = 0
    is_out = True
    while is_out :
        if type(data[0]) == list :
            count += 1
            data = data[0]
        else :
            count += 1
            is_out = False
    return count

In [62]:
a=[[1,2,3]]
h_ndim(a)

2

In [104]:
np.random.rand(5)

array([0.18758353, 0.45576685, 0.03406323, 0.69912612, 0.72994078])

In [105]:
def h_random_rand(num):
    box = []
    for i in range(num):
        box.append(ran.random())
    return box

In [125]:
h_random_rand(5)

[0.18631646002093183,
 0.6721081298312324,
 0.3345527043662292,
 0.10626223568111126,
 0.3659736535472389]

In [141]:
np.random.randint(3,10,5)

array([9, 5, 4, 6, 6])

In [153]:
def h_random_randint(min,max,num):
    box = []
    for i in range(num):
        box.append(ran.randint(min,max-1))
    return box

In [158]:
h_random_randint(3,10,5)

[4, 6, 3, 3, 8]

In [113]:
a=[4,5,7,3,1,7]
np.argmax(a)

2

In [111]:
def h_argmax(data):
    max=data[0]
    idx=0
    argmax=0
    for i in data:
        if i > max:
            max=i
            argmax=idx
        idx+=1
    return argmax

In [115]:
h_argmax(a)

2

In [117]:
np.argmin(a)

4

In [118]:
def h_argmin(data):
    min=data[0]
    idx=0
    argmin=0
    for i in data:
        if i < min:
            min=i
            argmin=idx
        idx+=1
    return argmin

In [120]:
h_argmin(a)

4

In [122]:
a=[4,5,7,3,1,7]
np.cumsum(a)

array([ 4,  9, 16, 19, 20, 27], dtype=int32)

In [123]:
def h_cumsum(data):
    sum=0
    cumsum=[]
    for i in data:
        sum+=i
        cumsum.append(sum)
    return cumsum

In [124]:
h_cumsum(a)

[4, 9, 16, 19, 20, 27]

In [160]:
a=[1,3,6,2,6,5,6]
b=[6,7,8,4,4,5,6]
np.equal(a,b)

array([False, False, False, False, False,  True,  True])

In [183]:
def h_equal(data1,data2):
    ndim=h_ndim(data1)
    box=[]
    if ndim == 1:
        for i in range(len(data1)):
            box.append('True' if data1[i] == data2[i] else 'False')
    elif ndim == 2:
        for i in range(len(data1)):
            mini=[]
            for j in range(len(data1[0])):
                mini.append('True' if data1[i][j] == data2[i][j] else 'False')
            box.append(mini)
    elif ndim == 3:
        for i in range(len(data1)):
            mini=[]
            for j in range(len(data1[0])):
                tiny=[]
                for k in range(len(data1[0][0])):
                    tiny.append('True' if data1[i][j][k] == data2[i][j][k] else 'False')
                mini.append(tiny)
            box.append(mini)
    return box

In [184]:
a=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
b=[[[4,2,3],[4,7,4]],[[1,2,3],[4,5,6]]]
h_equal(a,b)

[[['False', 'True', 'True'], ['True', 'False', 'False']],
 [['True', 'True', 'True'], ['True', 'True', 'True']]]

In [169]:
a=[1,3,6,2,6,5,6]
b=[6,7,8,4,4,5,6]
np.not_equal(a,b)

array([ True,  True,  True,  True,  True, False, False])

In [171]:
def h_not_equal(data1,data2):
    ndim=h_ndim(data1)
    box=[]
    if ndim == 1:
        for i in range(len(data1)):
            box.append('True' if data1[i] != data2[i] else 'False')
    elif ndim == 2:
        for i in range(len(data1)):
            mini=[]
            for j in range(len(data1[0])):
                mini.append('True' if data1[i][j] != data2[i][j] else 'False')
            box.append(mini)
    return box

In [173]:
a=[[1,2,3],[4,5,6]]
b=[[4,2,3],[4,7,4]]
h_not_equal(a,b)

[['True', 'False', 'False'], ['False', 'True', 'True']]

In [186]:
arr = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
arr

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [189]:
def gubin_array(arr):
    return arr

In [190]:
gubin_array([[[1,2],[3,4]],[[1,2],[3,4]]])

[[[1, 2], [3, 4]], [[1, 2], [3, 4]]]